[package]
name = "tatuin"
version = "0.13.2"
edition = "2024"
description = "Task Aggregator TUI for N providers"
homepage = "https://github.com/panter-dsd/tatuin"
license-file = "LICENSE.txt"
readme = "README.md"
rust-version = "1.86"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
color-eyre = "0.6.4"
colored = "3.0.0"
config = "0.15.11"
crossterm = { version = "0.29.0", features = ["event-stream"] }
itertools = "0.14.0"
ratatui = "0.29.0"
regex = "1.11.1"
reqwest = { version = "0.12.18", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha256 = "1.6.0"
strum = { version = "0.27.1", features = ["derive"] }
time = { version = "0.3.41", features = ["parsing", "formatting"] }
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
toml = "0.8.22"
url = "2.5.4"
url-builder = "0.1.1"
urlencoding = "2.1.3"
xdg = "3.0.0"
